using DotNet.Testcontainers.Containers;

using Npgsql;

using Opportunity.Testing.Images;
using Opportunity.Testing.Toxiproxy;

using Testcontainers.PostgreSql;

namespace Opportunity.Testing.Postgres;

/// <summary>
/// PostgreSQL (version from <c>versions.env</c>) behind Toxiproxy. Each test gets its own database cloned from
/// <see cref="TemplateDatabase"/>; override <see cref="SeedTemplateAsync"/> to apply schema/migrations once.
/// </summary>
public class PostgresFixture : DependencyFixture
{
    public const string TemplateDatabase = "opportunity_template";
    private const string HostAlias = "postgres";
    private const int Port = 5432;

    /// <summary>/dev/shm of the test server (Docker's default is 64 MiB).</summary>
    public const long PostgresShmBytes = 512L * 1024 * 1024;

    private readonly PostgreSqlContainer _container;

    public PostgresFixture()
    {
        _container = new PostgreSqlBuilder(ContainerImages.Postgres)
            .WithNetwork(Network)
            .WithNetworkAliases(HostAlias)
            .WithDatabase("postgres")
            .WithUsername("opportunity")
            .WithPassword("opportunity")
            // Durability is irrelevant for throwaway test data; trade it for speed.
            .WithCommand("-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off")
            // Every test gets its own database, and the cumulative statistics of all of them live in dynamic shared
            // memory (/dev/shm). Docker's 64 MiB default runs out late in a full run ("could not resize shared memory
            // segment ... No space left on device"), so give the server room.
            .WithCreateParameterModifier(parameters => (parameters.HostConfig ??= new Docker.DotNet.Models.HostConfig()).ShmSize = PostgresShmBytes)
            .Build();
    }

    /// <summary>Superuser connection string to the maintenance database (direct, not proxied).</summary>
    public string AdminConnectionString => new NpgsqlConnectionStringBuilder(_container.GetConnectionString()) { Pooling = false }.ConnectionString;

    protected override string NetworkAlias => HostAlias;

    protected override int ServicePort => Port;

    /// <summary>Creates an isolated database for one test from the template; dispose to drop it.</summary>
    public async Task<PostgresDatabase> CreateDatabaseAsync(CancellationToken cancellationToken = default)
    {
        var name = TestIsolation.NewName("t");
        await ExecuteAdminAsync($"CREATE DATABASE \"{name}\" TEMPLATE \"{TemplateDatabase}\"", cancellationToken).ConfigureAwait(false);
        return new PostgresDatabase(this, name);
    }

    /// <summary>Connection string for <paramref name="database"/>, optionally routed through a fault proxy.</summary>
    public string ConnectionString(string database, FaultProxy? via = null)
    {
        var builder = new NpgsqlConnectionStringBuilder(_container.GetConnectionString()) { Database = database };
        if (via is not null)
        {
            builder.Host = via.Host;
            builder.Port = via.Port;
        }

        return builder.ConnectionString;
    }

    internal Task DropDatabaseAsync(string name) =>
        ExecuteAdminAsync($"DROP DATABASE IF EXISTS \"{name}\" WITH (FORCE)", CancellationToken.None);

    /// <summary>Runs once, against the template database, before any test database is cloned.</summary>
    protected virtual Task SeedTemplateAsync(NpgsqlConnection connection, CancellationToken cancellationToken) => Task.CompletedTask;

    protected override IContainer DependencyContainer => _container;

    protected override async Task StartDependencyAsync()
    {
        await _container.StartAsync().ConfigureAwait(false);
        await ExecuteAdminAsync($"CREATE DATABASE \"{TemplateDatabase}\"", CancellationToken.None).ConfigureAwait(false);

        // Pooling off: CREATE DATABASE ... TEMPLATE fails while any session is connected to the template.
        var template = new NpgsqlConnectionStringBuilder(_container.GetConnectionString()) { Database = TemplateDatabase, Pooling = false };
        var connection = new NpgsqlConnection(template.ConnectionString);
        await using (connection.ConfigureAwait(false))
        {
            await connection.OpenAsync().ConfigureAwait(false);
            await SeedTemplateAsync(connection, CancellationToken.None).ConfigureAwait(false);
        }
    }

    protected override ValueTask StopDependencyAsync() => _container.DisposeAsync();

    private async Task ExecuteAdminAsync(string sql, CancellationToken cancellationToken)
    {
        var connection = new NpgsqlConnection(AdminConnectionString);
        await using (connection.ConfigureAwait(false))
        {
            await connection.OpenAsync(cancellationToken).ConfigureAwait(false);
#pragma warning disable CA2100 // Identifiers are generated by TestIsolation, never user input.
            var command = new NpgsqlCommand(sql, connection);
#pragma warning restore CA2100
            await using (command.ConfigureAwait(false))
            {
                await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
            }
        }
    }
}

/// <summary>A per-test database. Disposing drops it, terminating any connections still open.</summary>
public sealed class PostgresDatabase : IAsyncDisposable
{
    private readonly PostgresFixture _fixture;

    internal PostgresDatabase(PostgresFixture fixture, string name)
    {
        _fixture = fixture;
        Name = name;
    }

    public string Name { get; }

    /// <summary>Direct connection string.</summary>
    public string ConnectionString => _fixture.ConnectionString(Name);

    /// <summary>Connection string routed through <paramref name="proxy"/> for fault injection.</summary>
    public string ConnectionStringVia(FaultProxy proxy) => _fixture.ConnectionString(Name, proxy);

    public async ValueTask DisposeAsync() => await _fixture.DropDatabaseAsync(Name).ConfigureAwait(false);
}
