using System.Globalization;

using Microsoft.Extensions.DependencyInjection.Extensions;

using Opportunity.Api.Conventions;
using Opportunity.Api.Conventions.Idempotency;
using Opportunity.Api.Jobs;
using Opportunity.Application.Fields;
using Opportunity.Application.Jobs;
using Opportunity.Application.Productions;
using Opportunity.Application.Search;
using Opportunity.Application.Snapshots;
using Opportunity.Contracts.Api;
using Opportunity.Contracts.Search;
using Opportunity.Core.Productions;
using Opportunity.Core.Security;
using Opportunity.Core.Snapshots;
using Opportunity.Data.Fields;
using Opportunity.Data.Jobs;
using Opportunity.Data.Productions;
using Opportunity.Data.Snapshots;
using Opportunity.Production.Productions;
using Opportunity.Security.Authentication;
using Opportunity.Security.Authorization;

namespace Opportunity.Api.Productions;

/// <summary>
/// Productions (E12-T02, E12-T03): a frozen set plus a versioned specification, Bates numbers allocated by a job, and
/// finalization that freezes everything into a manifest. Every route needs <c>Production.Create</c>; finalizing and
/// voiding need <c>Production.Finalize</c>. Productions are shared by everyone holding <c>Production.Create</c> in the
/// workspace; listings of their documents leave out documents the caller may not view (Q-52). The volume itself (images,
/// natives, text, load files) is generated by E12-T05; its UI is E12-T08.
/// </summary>
public sealed class ProductionEndpoints : IApiEndpointModule
{
    public const string ProductionsPath = "/productions";

    private const string Tag = "Productions";
    private const string NotFoundDetail = "No such production.";

    public void MapEndpoints(ApiRouteGroups routes)
    {
        ArgumentNullException.ThrowIfNull(routes);
        var group = routes.Workspace.MapGroup(ProductionsPath);

        group.MapPost(string.Empty, CreateAsync)
            .RequirePermission(Permission.ProductionCreate)
            .WithName("CreateProduction")
            .WithTags(Tag)
            .WithSummary("Create a draft production of a frozen set, a saved search (frozen now) or as the next version of a finalized production.")
            .WithDescription(
                "The specification is validated and stored with every default filled in (canonical JSON and its SHA-256). A Bates start " +
                "number inside a range another production of the same prefix holds is refused (409).")
            .Produces<ProductionResource>(StatusCodes.Status201Created)
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status400BadRequest)
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status404NotFound)
            .ProducesProblem(StatusCodes.Status409Conflict)
            .ProducesProblem(StatusCodes.Status422UnprocessableEntity);

        group.MapGet(string.Empty, ListAsync)
            .RequirePermission(Permission.ProductionCreate)
            .WithName("ListProductions")
            .WithTags(Tag)
            .WithSummary("Productions of the workspace, newest first.")
            .Produces<CursorPage<ProductionResource>>()
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status404NotFound);

        group.MapGet("/bates-lookup", LookupAsync)
            .RequirePermission(Permission.ProductionCreate)
            .WithName("LookupBates")
            .WithTags(Tag)
            .WithSummary("Bates cross-reference: the document behind a Bates number (?number=ABC0000123), or a document's numbers (?documentId=).")
            .WithDescription("Searches produced, voided and allocated draft productions; discarded drafts' numbers were never issued. Documents you may not view are only counted.")
            .Produces<BatesLookupResource>()
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status404NotFound);

        group.MapGet("/{productionId}", GetAsync)
            .RequirePermission(Permission.ProductionCreate)
            .WithName("GetProduction")
            .WithTags(Tag)
            .WithSummary("One production with its specification, Bates range, integrity check, manifest and ETag.")
            .Produces<ProductionResource>()
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status404NotFound);

        group.MapPut("/{productionId}", UpdateAsync)
            .RequirePermission(Permission.ProductionCreate)
            .WithName("UpdateProduction")
            .WithTags(Tag)
            .WithSummary("Replace a draft's specification, name or frozen set (If-Match required). Releases any Bates allocation; finalized productions never change (409).")
            .Produces<ProductionResource>()
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status404NotFound)
            .ProducesProblem(StatusCodes.Status409Conflict)
            .ProducesProblem(StatusCodes.Status412PreconditionFailed)
            .ProducesProblem(StatusCodes.Status428PreconditionRequired);

        group.MapPost("/{productionId}/bates-allocation", AllocateAsync)
            .RequirePermission(Permission.ProductionCreate)
            .WithName("AllocateProductionBates")
            .WithTags(Tag)
            .WithSummary("Allocate the draft's Bates numbers (202 with the job): production order keeps families together; placeholders and slip sheets take one number.")
            .WithDescription(
                "The range is reserved only if it overlaps no other production's numbers of the same prefix; after the job an integrity check " +
                "(no duplicates in the matter, no unattributed gaps, families adjacent) decides whether the allocation stands.")
            .RequireIdempotencyKey()
            .Produces<JobResource>(StatusCodes.Status202Accepted)
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status404NotFound)
            .ProducesProblem(StatusCodes.Status409Conflict);

        group.MapPost("/{productionId}/finalize", FinalizeAsync)
            .RequirePermission(Permission.ProductionFinalize)
            .WithName("FinalizeProduction")
            .WithTags(Tag)
            .WithSummary("Finalize an allocated draft (If-Match required): specification, membership and Bates numbers are frozen and recorded in the manifest.")
            .WithDescription(
                "409 PRIVILEGE_WITHHELD while members are coded Withhold; 409 PRIVILEGE_CONFLICTS while members' families or duplicate " +
                "groups have unresolved privilege conflicts (E13-T02), unless the body gives privilegeConflictOverride with a reason " +
                "(needs PrivilegeLog.Generate; recorded in the manifest and audited). Neither answer counts or names documents.")
            .Produces<ProductionResource>()
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status404NotFound)
            .ProducesProblem(StatusCodes.Status409Conflict)
            .ProducesProblem(StatusCodes.Status412PreconditionFailed)
            .ProducesProblem(StatusCodes.Status428PreconditionRequired);

        group.MapPost("/{productionId}/void", VoidAsync)
            .RequirePermission(Permission.ProductionFinalize)
            .WithName("VoidProduction")
            .WithTags(Tag)
            .WithSummary("Void a finalized production with a reason (If-Match required); its Bates numbers are never issued again.")
            .Produces<ProductionResource>()
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status404NotFound)
            .ProducesProblem(StatusCodes.Status409Conflict)
            .ProducesProblem(StatusCodes.Status412PreconditionFailed)
            .ProducesProblem(StatusCodes.Status428PreconditionRequired);

        group.MapPost("/{productionId}/discard", DiscardAsync)
            .RequirePermission(Permission.ProductionCreate)
            .WithName("DiscardProduction")
            .WithTags(Tag)
            .WithSummary("Discard a draft (If-Match required); its never-produced Bates numbers become free again (Q-54).")
            .Produces<ProductionResource>()
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status404NotFound)
            .ProducesProblem(StatusCodes.Status409Conflict)
            .ProducesProblem(StatusCodes.Status412PreconditionFailed)
            .ProducesProblem(StatusCodes.Status428PreconditionRequired);

        group.MapGet("/{productionId}/documents", ListDocumentsAsync)
            .RequirePermission(Permission.ProductionCreate)
            .WithName("ListProductionDocuments")
            .WithTags(Tag)
            .WithSummary("The production's documents in production order with ProdBegBates, ProdEndBates, ProdBegAttach and ProdEndAttach.")
            .Produces<CursorPage<ProductionDocumentResource>>()
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status404NotFound);

        group.MapPost("/{productionId}/verification", VerifyAsync)
            .RequirePermission(Permission.ProductionCreate)
            .WithName("VerifyProduction")
            .WithTags(Tag)
            .WithSummary("Re-verify the production against its manifest: specification, frozen set and a re-run of the Bates allocation; differences are listed and audited.")
            .Produces<ProductionVerificationResource>()
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status404NotFound)
            .ProducesProblem(StatusCodes.Status409Conflict);
    }

    internal static async Task<IResult> CreateAsync(
        string workspaceId, CreateProductionRequest request, HttpContext context, ProductionService service, IJobRepository jobs,
        CancellationToken cancellationToken)
    {
        _ = workspaceId;
        if (context.GetWorkspaceAccess() is not { } access)
        {
            return Problems.NotFound();
        }

        if (request is null)
        {
            return Problems.Validation(new Dictionary<string, string[]> { ["body"] = ["Send the production request."] });
        }

        var sources = (request.SnapshotId is null ? 0 : 1) + (request.SavedSearchId is null ? 0 : 1) + (request.PreviousVersionId is null ? 0 : 1);
        if (sources != 1)
        {
            return Problems.Validation(new Dictionary<string, string[]>
            {
                ["snapshotId"] = ["Give exactly one of snapshotId, savedSearchId and previousVersionId."],
            });
        }

        var snapshotId = request.SnapshotId;
        if (request.SavedSearchId is { } savedSearchId)
        {
            switch (await FreezeSavedSearchAsync(context, access.Principal, access.WorkspaceId, savedSearchId, request.Name, cancellationToken).ConfigureAwait(false))
            {
                case { Problem: { } problem }:
                    return problem;
                case { SnapshotId: { } frozen }:
                    snapshotId = frozen;
                    break;
            }
        }

        var outcome = await service.CreateAsync(access.Principal, access.WorkspaceId, request, snapshotId, cancellationToken).ConfigureAwait(false);
        if (outcome.Status != ProductionOutcomeStatus.Ok)
        {
            return Problem(outcome);
        }

        SetETag(context, outcome.Production!);
        return TypedResults.Created(
            $"{ApiRoutes.V1Prefix}/workspaces/{access.WorkspaceId}{ProductionsPath}/{outcome.Production!.ProductionId}",
            await ResourceAsync(outcome.Production, jobs, cancellationToken).ConfigureAwait(false));
    }

    internal static async Task<IResult> ListAsync(
        string workspaceId, [AsParameters] PageQuery page, HttpContext context, IProductionStore productions, IJobRepository jobs,
        CancellationToken cancellationToken)
    {
        _ = workspaceId;
        if (context.GetWorkspaceAccess() is not { } access)
        {
            return Problems.NotFound();
        }

        if (page.Validate() is { } invalid)
        {
            return invalid;
        }

        ProductionListCursor? after = null;
        if (page.Cursor is { } cursor)
        {
            if (PageCursor.Decode(cursor, access.Principal.UserId, access.WorkspaceId, 2) is not [var ticks, var id]
                || !long.TryParse(ticks, NumberStyles.None, CultureInfo.InvariantCulture, out var t) || !Guid.TryParse(id, out var productionId))
            {
                return PageCursor.Invalid();
            }

            after = new ProductionListCursor(new DateTimeOffset(t, TimeSpan.Zero), productionId);
        }

        var limit = page.EffectiveLimit;
        var records = await productions.ListAsync(access.WorkspaceId, after, limit + 1, cancellationToken).ConfigureAwait(false);
        var items = new List<ProductionResource>();
        foreach (var record in records.Take(limit))
        {
            items.Add(await ResourceAsync(record, jobs, cancellationToken).ConfigureAwait(false));
        }

        var next = records.Count > limit
            ? PageCursor.Encode(access.Principal.UserId, access.WorkspaceId,
                records[limit - 1].CreatedAt.UtcTicks.ToString(CultureInfo.InvariantCulture), records[limit - 1].ProductionId.ToString("N"))
            : null;
        return TypedResults.Ok(new CursorPage<ProductionResource>(items, next,
            new TotalCount(items.Count, next is null && after is null ? TotalRelation.Eq : TotalRelation.Gte)));
    }

    internal static async Task<IResult> GetAsync(
        string workspaceId, string productionId, HttpContext context, IProductionStore productions, IJobRepository jobs, CancellationToken cancellationToken)
    {
        _ = workspaceId;
        if (await CurrentAsync(context, productionId, productions, cancellationToken).ConfigureAwait(false) is not { } production)
        {
            return Problems.NotFound(NotFoundDetail);
        }

        SetETag(context, production);
        return TypedResults.Ok(await ResourceAsync(production, jobs, cancellationToken).ConfigureAwait(false));
    }

    internal static async Task<IResult> UpdateAsync(
        string workspaceId, string productionId, UpdateProductionRequest request, HttpContext context, IProductionStore productions,
        ProductionService service, IJobRepository jobs, CancellationToken cancellationToken)
    {
        _ = workspaceId;
        if (await CurrentAsync(context, productionId, productions, cancellationToken).ConfigureAwait(false) is not { } current)
        {
            return Problems.NotFound(NotFoundDetail);
        }

        if (EntityTags.CheckIfMatch(context.Request, current.RowVersion) is { } precondition)
        {
            return precondition;
        }

        if (request?.Specification is null)
        {
            return Problems.Validation(new Dictionary<string, string[]> { ["specification"] = ["Send the full specification."] });
        }

        var access = context.GetWorkspaceAccess()!;
        var outcome = await service.UpdateAsync(access.Principal, access.WorkspaceId, current.ProductionId, current.RowVersion, request, cancellationToken)
            .ConfigureAwait(false);
        return await ResultAsync(context, outcome, jobs, cancellationToken).ConfigureAwait(false);
    }

    internal static async Task<IResult> AllocateAsync(
        string workspaceId, string productionId, HttpContext context, IProductionStore productions, ProductionService service,
        CancellationToken cancellationToken)
    {
        _ = workspaceId;
        if (await CurrentAsync(context, productionId, productions, cancellationToken).ConfigureAwait(false) is not { } current)
        {
            return Problems.NotFound(NotFoundDetail);
        }

        var access = context.GetWorkspaceAccess()!;
        var key = context.Request.Headers[IdempotencyMiddleware.HeaderName].ToString();
        var outcome = await service.AllocateAsync(access.Principal, access.WorkspaceId, current.ProductionId, key.Length > 0 ? key : null, cancellationToken)
            .ConfigureAwait(false);
        if (outcome.Status != ProductionOutcomeStatus.Ok)
        {
            return Problem(outcome);
        }

        if (outcome.Job is not { } job)
        {
            return Problems.Create(StatusCodes.Status409Conflict, ProblemCodes.Conflict, "The allocation job could not be read; try again.");
        }

        return ApiResults.JobAccepted(access.WorkspaceId.ToString(), job.JobId.ToString(), JobEndpoints.ToResource(job));
    }

    internal static async Task<IResult> FinalizeAsync(
        string workspaceId, string productionId, FinalizeProductionRequest? request, HttpContext context, IProductionStore productions,
        ProductionService service, IJobRepository jobs, CancellationToken cancellationToken)
    {
        _ = workspaceId;
        if (await CurrentAsync(context, productionId, productions, cancellationToken).ConfigureAwait(false) is not { } current)
        {
            return Problems.NotFound(NotFoundDetail);
        }

        if (EntityTags.CheckIfMatch(context.Request, current.RowVersion) is { } precondition)
        {
            return precondition;
        }

        var access = context.GetWorkspaceAccess()!;
        if (request?.PrivilegeConflictOverride is { Reason: null })
        {
            return Problems.Validation(new Dictionary<string, string[]>
            {
                ["privilegeConflictOverride.reason"] = ["Give the reason for overriding the privilege conflicts."],
            });
        }

        var outcome = await service.FinalizeAsync(access.Principal, access.WorkspaceId, current.ProductionId, current.RowVersion,
            request?.PrivilegeConflictOverride?.Reason, cancellationToken).ConfigureAwait(false);
        return await ResultAsync(context, outcome, jobs, cancellationToken).ConfigureAwait(false);
    }

    internal static async Task<IResult> VoidAsync(
        string workspaceId, string productionId, VoidProductionRequest request, HttpContext context, IProductionStore productions, ProductionService service,
        IJobRepository jobs, CancellationToken cancellationToken)
    {
        _ = workspaceId;
        if (await CurrentAsync(context, productionId, productions, cancellationToken).ConfigureAwait(false) is not { } current)
        {
            return Problems.NotFound(NotFoundDetail);
        }

        if (EntityTags.CheckIfMatch(context.Request, current.RowVersion) is { } precondition)
        {
            return precondition;
        }

        var access = context.GetWorkspaceAccess()!;
        var outcome = await service.VoidAsync(access.Principal, access.WorkspaceId, current.ProductionId, current.RowVersion, request?.Reason, cancellationToken)
            .ConfigureAwait(false);
        return await ResultAsync(context, outcome, jobs, cancellationToken).ConfigureAwait(false);
    }

    internal static async Task<IResult> DiscardAsync(
        string workspaceId, string productionId, HttpContext context, IProductionStore productions, ProductionService service, IJobRepository jobs,
        CancellationToken cancellationToken)
    {
        _ = workspaceId;
        if (await CurrentAsync(context, productionId, productions, cancellationToken).ConfigureAwait(false) is not { } current)
        {
            return Problems.NotFound(NotFoundDetail);
        }

        if (EntityTags.CheckIfMatch(context.Request, current.RowVersion) is { } precondition)
        {
            return precondition;
        }

        var access = context.GetWorkspaceAccess()!;
        var outcome = await service.DiscardAsync(access.Principal, access.WorkspaceId, current.ProductionId, current.RowVersion, cancellationToken).ConfigureAwait(false);
        return await ResultAsync(context, outcome, jobs, cancellationToken).ConfigureAwait(false);
    }

    internal static async Task<IResult> ListDocumentsAsync(
        string workspaceId, string productionId, [AsParameters] PageQuery page, HttpContext context, IProductionStore productions,
        ProductionService service, CancellationToken cancellationToken)
    {
        _ = workspaceId;
        if (page.Validate() is { } invalid)
        {
            return invalid;
        }

        if (await CurrentAsync(context, productionId, productions, cancellationToken).ConfigureAwait(false) is not { } production)
        {
            return Problems.NotFound(NotFoundDetail);
        }

        var access = context.GetWorkspaceAccess()!;
        long after = 0;
        if (page.Cursor is { } cursor
            && (PageCursor.Decode(cursor, access.Principal.UserId, access.WorkspaceId, 2) is not [var id, var sequence]
                || id != production.ProductionId.ToString("N") || !long.TryParse(sequence, NumberStyles.None, CultureInfo.InvariantCulture, out after)))
        {
            return PageCursor.Invalid();
        }

        var limit = page.EffectiveLimit;
        var (rows, restricted, last) = await service.ListDocumentsAsync(access.Principal, access.WorkspaceId, production.ProductionId, after, limit, cancellationToken)
            .ConfigureAwait(false);
        var items = rows.Select(r => new ProductionDocumentResource(r.Sequence, r.DocumentId, r.ControlNumber, ProductionSpecificationRules.Resource(r.Output),
            r.Units, r.ProdBegBates, r.ProdEndBates, r.ProdBegAttach, r.ProdEndAttach)).ToList();
        var next = last is { } l && rows.Count + restricted == limit
            ? PageCursor.Encode(access.Principal.UserId, access.WorkspaceId, production.ProductionId.ToString("N"), l.ToString(CultureInfo.InvariantCulture))
            : null;
        return TypedResults.Ok(new CursorPage<ProductionDocumentResource>(items, next,
            new TotalCount(items.Count, next is null && after == 0 ? TotalRelation.Eq : TotalRelation.Gte)));
    }

    internal static async Task<IResult> VerifyAsync(
        string workspaceId, string productionId, HttpContext context, IProductionStore productions, ProductionService service,
        DocumentSetSnapshotService snapshots, CancellationToken cancellationToken)
    {
        _ = workspaceId;
        if (await CurrentAsync(context, productionId, productions, cancellationToken).ConfigureAwait(false) is not { } production)
        {
            return Problems.NotFound(NotFoundDetail);
        }

        var access = context.GetWorkspaceAccess()!;
        var (outcome, verification) = await service.VerifyAsync(access.Principal, access.WorkspaceId, production.ProductionId, snapshots, cancellationToken)
            .ConfigureAwait(false);
        if (verification is null)
        {
            return Problem(outcome);
        }

        return TypedResults.Ok(new ProductionVerificationResource(verification.Consistent, verification.Differences, Integrity(verification.Integrity)));
    }

    internal static async Task<IResult> LookupAsync(
        string workspaceId, string? number, string? documentId, HttpContext context, ProductionService service, CancellationToken cancellationToken)
    {
        _ = workspaceId;
        if (context.GetWorkspaceAccess() is not { } access)
        {
            return Problems.NotFound();
        }

        Guid? document = null;
        if (string.IsNullOrWhiteSpace(number) == string.IsNullOrWhiteSpace(documentId)
            || (documentId is not null && !Guid.TryParse(documentId, out _))
            || (number is not null && number.Trim().Length > 100))
        {
            return Problems.Validation(new Dictionary<string, string[]>
            {
                ["number"] = ["Give either a Bates number (at most 100 characters) or a documentId."],
            });
        }

        if (documentId is not null)
        {
            document = Guid.Parse(documentId);
        }

        var (matches, restricted) = await service.LookupAsync(access.Principal, access.WorkspaceId, number, document, cancellationToken).ConfigureAwait(false);
        return TypedResults.Ok(new BatesLookupResource(
            [.. matches.Select(m => new BatesLookupMatch(m.ProductionId, m.ProductionName, m.ProductionVersion, Status(m.ProductionStatus), m.DocumentId,
                m.ControlNumber, m.ProdBegBates, m.ProdEndBates, m.ProdBegAttach, m.ProdEndAttach))],
            new TotalCount(matches.Count, TotalRelation.Eq),
            restricted));
    }

    private sealed record FreezeResult(Guid? SnapshotId, IResult? Problem);

    /// <summary>Freezes a saved search the caller can see into a Production frozen set, as <c>POST …/snapshots</c> does.</summary>
    private static async Task<FreezeResult> FreezeSavedSearchAsync(
        HttpContext context, Application.Authorization.SecurityPrincipal principal, Guid workspaceId, Guid savedSearchId, string? name,
        CancellationToken cancellationToken)
    {
        var services = context.RequestServices;
        if (services.GetService<ISavedSearchQueries>() is not { } savedSearches
            || await savedSearches.FindForRunAsync(principal, workspaceId, savedSearchId, cancellationToken).ConfigureAwait(false) is not { } saved)
        {
            return new FreezeResult(null, Problems.NotFound("No such saved search."));
        }

        var session = Guid.TryParse(context.User.FindFirst(OpportunityClaimTypes.SessionId)?.Value, out var sid) ? sid : (Guid?)null;
        var snapshots = services.GetRequiredService<DocumentSetSnapshotService>();
        var outcome = await snapshots.CreateAsync(new SearchCaller(principal, workspaceId, session), new SnapshotCreateRequest(
            SnapshotPurpose.Production,
            string.IsNullOrWhiteSpace(name) ? null : name.Trim(),
            $"{SavedSearchQuerySyntax.FieldName}:{savedSearchId:D}",
            Expansion: saved.Expansion), cancellationToken).ConfigureAwait(false);
        switch (outcome.Status)
        {
            case SnapshotCreateStatus.Ready:
                return new FreezeResult(outcome.Snapshot!.SnapshotId, null);
            case SnapshotCreateStatus.Accepted:
                services.GetService<Snapshots.SnapshotMaterializationSignal>()?.Nudge(workspaceId, outcome.Snapshot!.SnapshotId);
                return new FreezeResult(outcome.Snapshot!.SnapshotId, null);
            case SnapshotCreateStatus.InvalidRequest or SnapshotCreateStatus.InvalidQuery:
                return new FreezeResult(null, Problems.Validation(new Dictionary<string, string[]>
                {
                    ["savedSearchId"] = ["The saved search cannot be run; open it to see why."],
                }));
            case SnapshotCreateStatus.Forbidden:
                return new FreezeResult(null, Problems.Create(StatusCodes.Status403Forbidden, ProblemCodes.Forbidden, "You do not have permission for this operation."));
            case SnapshotCreateStatus.TooLarge:
                return new FreezeResult(null, Problems.Create(StatusCodes.Status422UnprocessableEntity, ProblemCodes.UnprocessableContent,
                    "The saved search selects more documents than a frozen set may hold."));
            case SnapshotCreateStatus.Failed:
                return new FreezeResult(null, Problems.Create(StatusCodes.Status503ServiceUnavailable, ProblemCodes.ServiceUnavailable,
                    "The selection changed while it was being frozen; try again."));
            default:
                return new FreezeResult(null, Problems.NotFound("No such saved search."));
        }
    }

    private static async Task<ProductionRecord?> CurrentAsync(HttpContext context, string productionId, IProductionStore productions, CancellationToken cancellationToken) =>
        context.GetWorkspaceAccess() is { } access && Guid.TryParse(productionId, out var id)
            ? await productions.GetAsync(access.WorkspaceId, id, cancellationToken).ConfigureAwait(false)
            : null;

    private static async Task<IResult> ResultAsync(HttpContext context, ProductionOutcome outcome, IJobRepository jobs, CancellationToken cancellationToken)
    {
        if (outcome.Status != ProductionOutcomeStatus.Ok)
        {
            return Problem(outcome);
        }

        SetETag(context, outcome.Production!);
        return TypedResults.Ok(await ResourceAsync(outcome.Production!, jobs, cancellationToken).ConfigureAwait(false));
    }

    private static IResult Problem(ProductionOutcome outcome) => outcome.Status switch
    {
        ProductionOutcomeStatus.Invalid => Problems.Validation(outcome.Errors!.ToDictionary()),
        ProductionOutcomeStatus.NotFound => Problems.NotFound(NotFoundDetail),
        ProductionOutcomeStatus.VersionConflict => Problems.Create(StatusCodes.Status412PreconditionFailed, ProblemCodes.VersionConflict,
            "The production was modified since it was read."),
        ProductionOutcomeStatus.BatesConflict => TypedResults.Problem(
            statusCode: StatusCodes.Status409Conflict,
            detail: outcome.Reason,
            type: ProblemCodes.TypeFor(ProblemCodes.Conflict),
            extensions: new Dictionary<string, object?> { [Problems.CodeExtension] = ProblemCodes.Conflict, ["reason"] = "BATES_OVERLAP" }),
        ProductionOutcomeStatus.PrivilegeWithheld => TypedResults.Problem(
            statusCode: StatusCodes.Status409Conflict,
            title: "Documents are withheld for privilege",
            detail: outcome.Reason,
            type: ProblemCodes.TypeFor(ProblemCodes.Conflict),
            extensions: new Dictionary<string, object?> { [Problems.CodeExtension] = ProblemCodes.Conflict, ["reason"] = "PRIVILEGE_WITHHELD" }),
        ProductionOutcomeStatus.PrivilegeConflicts => TypedResults.Problem(
            statusCode: StatusCodes.Status409Conflict,
            title: "Unresolved privilege conflicts",
            detail: outcome.Reason,
            type: ProblemCodes.TypeFor(ProblemCodes.Conflict),
            extensions: new Dictionary<string, object?> { [Problems.CodeExtension] = ProblemCodes.Conflict, ["reason"] = "PRIVILEGE_CONFLICTS" }),
        ProductionOutcomeStatus.Forbidden => Problems.Create(StatusCodes.Status403Forbidden, ProblemCodes.Forbidden,
            outcome.Reason ?? "You do not have permission for this operation."),
        _ => Problems.Create(StatusCodes.Status409Conflict, ProblemCodes.Conflict, outcome.Reason ?? "The production's state does not allow this."),
    };

    private static void SetETag(HttpContext context, ProductionRecord production) =>
        context.Response.Headers.ETag = EntityTags.ForVersion(production.RowVersion);

    internal static async Task<ProductionResource> ResourceAsync(ProductionRecord production, IJobRepository jobs, CancellationToken cancellationToken)
    {
        var job = production.BatesJobId is { } jobId ? await jobs.GetAsync(production.WorkspaceId, jobId, cancellationToken).ConfigureAwait(false) : null;
        return ToResource(production, job);
    }

    internal static ProductionResource ToResource(ProductionRecord production, JobInfo? job)
    {
        var format = new BatesFormat(production.BatesPrefix, production.BatesPadding, production.BatesSuffix, BatesNumberingLevel.Page);
        return new ProductionResource(
            production.ProductionId,
            production.WorkspaceId,
            production.LineageId,
            production.Version,
            production.Name,
            production.SnapshotId,
            Status(production.Status),
            ProductionSpecificationRules.Deserialize(production.SpecificationJson),
            Convert.ToHexStringLower(production.SpecificationSha256),
            new ProductionBatesResource(
                Enum.Parse<BatesAllocationStateResource>(production.BatesState.ToString()),
                production.BatesReason,
                production.BatesFirst is { } f ? format.Format(f) : null,
                production.BatesLast is { } l && l >= 1 ? format.Format(l) : null,
                production.BatesFirst,
                production.BatesLast,
                production.BatesDocuments,
                production.BatesUnits,
                production.AssignmentsSha256 is { } a ? Convert.ToHexStringLower(a) : null,
                BatesIntegrityReport.FromJson(production.IntegrityJson) is { } integrity ? Integrity(integrity) : null),
            production.Manifest,
            production.ManifestSha256 is { } m ? Convert.ToHexStringLower(m) : null,
            production.CreatedBy,
            production.CreatedAt,
            production.ModifiedAt,
            production.FinalizedAt,
            production.VoidedAt,
            production.VoidReason,
            production.DiscardedAt,
            job is null ? null : JobEndpoints.ToResource(job));
    }

    private static ProductionIntegrityResource Integrity(BatesIntegrityReport report) => new(
        report.Passed, report.Documents, report.Numbers, report.Placeholders, report.NativeSlipSheets, report.Gaps, report.Problems);

    private static ProductionStatusResource Status(ProductionStatus status) => Enum.Parse<ProductionStatusResource>(status.ToString());
}

public static class ProductionEndpointRegistration
{
    /// <summary>The production API with its stores (the snapshot service comes with the snapshot endpoints).</summary>
    public static IServiceCollection AddProductionEndpoints(this IServiceCollection services)
    {
        ArgumentNullException.ThrowIfNull(services);
        services.AddPostgresProductionStore();
        services.AddPostgresSnapshotStore();
        services.TryAddSingleton<IJobRepository, JobRepository>();
        services.TryAddSingleton<IFieldCatalogRepository, FieldCatalogRepository>();
        services.TryAddSingleton<IFieldAccessFilter, UnrestrictedFieldAccess>();
        services.AddProductionService();
        services.AddSingleton<IApiEndpointModule, ProductionEndpoints>();
        return services;
    }
}
